### ISSUE TITLE
Transaction auto fetch reference block ID

### ISSUE THREAD

**Issue by janezpodhostnik** [janezpodhostnik/flow-py-sdk#14]
When creating a `Tx` object a reference block ID must be specified.

Introduce an optional way for the Tx object to fetch the reference block ID behind the scenes.

**Comment by barekati** [comment]
what do you think about using `client.get_latest_block(is_sealed=False)` in background? if user don't pass a specific block him/herself, `reference_block_id` field can fill with `client.get_latest_block(is_sealed=False)` automatically.

**Comment by janezpodhostnik** [comment]
Yes! This is exactly what I had in mind here! Sorry for the poor description.
