### ISSUE TITLE
Status of python sdk

### ISSUE THREAD

**Issue by AndriyMulyar** [janezpodhostnik/flow-py-sdk#16]
Hi,

Thanks for starting this project. What remains to be implemented and tested to make this sdk stable?

Thanks!

**Comment by janezpodhostnik** [comment]
Hi AndriyMulyar. Thank you for your interest.

I'm trying to release an MVP version soon.

Which for me would mean that all the functionality to interact with the FLOW blockchain is there:

- being able to decode/encode json cadence values
- sending scripts and getting results
- sending/signing arbitrary transactions
- getting events/transaction/blocks/accounts from the FLOW grpc
- having CI that runs tests and examples on PRs
- having a lot of tests and good usage documentation

All of the above except the last point is actually covered already. I'm hoping to get that last point covered in the following weeks.

There are certainly still bugs and instabilities, but at the moment there are no **known** bugs or instabilities :sweat_smile:. There is a CI pipeline in place to run all the tests (there aren't that many right now) and all of the examples on the most recent emulator version on every release (an on PRs). Which means there is little chance of something really breaking getting released.

I have been using the `flow-py-sdk` for my own projects and I'm also trying to create a public showcase project, so I know for a fact it **can** be used.

I would appreciate any feedback from anyone using or wanting to use this SDK. Feedback would make development much faster :smile:.

**Comment by AndriyMulyar** [comment]
Awesome, thank you for the detailed response.
