### ISSUE TITLE
Broken URL in python page.

### ISSUE THREAD

**Issue by Captain272** [janezpodhostnik/flow-py-sdk#57]
The guide URL provided on the python page for flow_py_sdk is broken. 

The link in the python page is:  https://janezpodhostnik.github.io/flow-py-sdk

Correct Link:  https://janezpodhostnik.github.io/flow-py-sdk/python_SDK_guide/

**Comment by janezpodhostnik** [comment]
Thank you very much for reporting.
It was already fixed in the past, but a version was never released. 
Released a new version, and the link works now.

**Comment by Captain272** [comment]
Thank you for responding.
